### PR TITLE
Add support Travis CI and requirements.txt

### PR DESCRIPTION
**Pull request by Hatollint**
Add .travis.yml with settings and requirements.txt to easy and fast install with pip.
P.S: It is necessary to write a tests to Travis CI. I do not know how to do it with Google App Engine

### CODE REVIEW

**Comment by m-murad** [comment]
Activate travis on your repo and show if its working or not

**Comment by m-murad** [comment]
Send me screenshots to show that travis is building on your repository.

**Comment by Hatollint** [comment]
@m-murad Its work 💯 
screenshot_15
screenshot_17

**Comment by m-murad** [comment]
Nice please share the link of the associated gci task.

**Comment by m-murad** [comment]
no need, approved task.

**Pull request merged**
